apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image:  antonyjebinraj/fastapi-ascendo:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1 
kind: Service
metadata:
  name: fastapi-service
spec:
  type: ClusterIP
  selector:
    component: fastapi-service
  ports:
    - port: 8000
      targetPort: 8001