version: "3.7"

services:
  app:
    build: .
    image: fastapi
    container_name: app
    volumes:
      - ./:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://fastapi:fastapi@db/fastapi

  db:
    image: postgres:12.1-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi

volumes:
  postgres_data: